name: Update Newsletter page from Substack

on:
  schedule:
    - cron: "0 0 */31 * *" # Run every 31 days at midnight UTC
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  goodreads:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master

      - name: Install dependencies
        run: npm install

      - name: Fetch newsletter issues from Substack
        run: node ./src/utils/newsletter.js

      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            chore: fetch newsletter issues
            skip-checks: true
        run: |
          git config user.email "${{ secrets.YOUR_EMAIL }}"
          git config user.name "Alexandre Mouriec"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/mrcalexandre/alexandremouriec.com.git
          git checkout main
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin main)
