name: Webmentions

on:
  schedule:
    - cron: "0 0 */7 * *" # Run every 7 days at midnight UTC
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Fetch webmentions
        env:
          WEBMENTION_API_KEY: ${{ secrets.WEBMENTION_API_KEY }}
        run: node ./src/utils/webmentions.js

      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            add webmentions
            skip-checks: true
        run: |
          git config user.email ${{ secrets.YOUR_EMAIL }}
          git config user.name "Alexandre Mouriec"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/mrcalexandre/your-project.git
          git checkout main
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin main)
